### ISSUE TITLE
Name conflict with an earlier `bnmr` package: perhaps, rename the package?

### ISSUE THREAD

**Issue by barracuda156** [sjl-sjtu/bnmr#1]
@sjl-sjtu There is already another `bnmr` package, and duplicate naming creates a conflict and makes it impossible to install both (or at least have both active): https://github.com/AnderWilson/bnmr
It has been committed in 2019, so perhaps it is fair to consider the name be “reserved”: https://github.com/AnderWilson/bnmr/commit/84e93b08206b2a22b1b55bd7359ec9512323baa4 (I have no personal association with that project, I just bumped into the problem after looking for `bnmr` from a journal publication).
This package was committed in 2021: https://github.com/sjl-sjtu/bnmr/commit/0cdf7f6b63c8eb7797c61873a95d99b7dce55987

Perhaps rename it and resolve the conflict?

**Comment by sjl-sjtu** [comment]
Dear Sergey,

Thank you for your email.

Sorry for not noticing the existence of the R package with the same name earlier. I will make the necessary changes to our R package's name. However, since the project is currently under review, changing the GitHub branch name now might make it difficult for the reviewers to locate the associated link. Therefore, please allow me to wait for the review feedback before making changes to the name.

Best regards,

Jianle

**Comment by sjl-sjtu** [comment]
Dear Sergey,

Thank you for your email.

Sorry for not noticing the existence of the R package with the same name earlier. I will make the necessary changes to our R package's name. However, since the project is currently under review, changing the GitHub branch name now might make it difficult for the reviewers to locate the associated link. Therefore, please allow me to wait for the review feedback before making changes to the name.

Best regards,

Jianle

----- Original Message -----
From: "Sergey Fedorov" ***@***.***>
To: "sjl-sjtu/bnmr" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, December 29, 2023 1:49:53 PM
Subject: [sjl-sjtu/bnmr] Name conflict with an earlier `bnmr` package: perhaps, rename the package? (Issue #1)

There is already another `bnmr` package, which will create a conflict and make it impossible to install both (or at least have both active): https://github.com/AnderWilson/bnmr
It has been committed in 2019, so perhaps it is fair to consider the name be “reserved”: https://github.com/AnderWilson/bnmr/commit/84e93b08206b2a22b1b55bd7359ec9512323baa4 (I have no personal association with that project, I just bumped into the problem after looking for `bnmr` from a journal publication).
This package was committed in 2021: https://github.com/sjl-sjtu/bnmr/commit/0cdf7f6b63c8eb7797c61873a95d99b7dce55987

Perhaps rename it and resolve the conflict?

-- 
Reply to this email directly or view it on GitHub:
https://github.com/sjl-sjtu/bnmr/issues/1

**Comment by barracuda156** [comment]
@sjl-sjtu Thank you. As long as it is done prior to publication on CRAN, all should be good.

**Comment by sjl-sjtu** [comment]
I have already renamed the package to `bnmr2` to avoid conflict. Thank you for your feedback again.

**Comment by barracuda156** [comment]
@sjl-sjtu Great, thanks for addressing this!

**Comment by barracuda156** [comment]
@sjl-sjtu Just FYI, `bnmr2` has been added to Macports now: https://github.com/macports/macports-ports/pull/22416/commits/028d195a3022c629db7a25d9fbb6779460e638c1

Should be available shortly upon `port sync` and installable via `sudo port install R-bnmr2`.
